#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

class CAffect
{
	public:
		DWORD	dwType;
		BYTE	bApplyOn;
		long	lApplyValue;
		DWORD   dwFlag;
		long	lDuration;
		long	lSPCost;

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED		= 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,	
	AFFECT_INT,	
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,		// 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226

	AFFECT_ATTBONUS_ANIMAL, 
	AFFECT_ATTBONUS_ORC,
	AFFECT_ATTBONUS_MILGYO,
	AFFECT_ATTBONUS_UNDEAD,		// 230
	AFFECT_ATTBONUS_DEVIL,
	AFFECT_STUN_PCT,
	AFFECT_MAX_HP,
	AFFECT_MAX_SP,
	AFFECT_ATTBONUS_WARRIOR,	// 235
	AFFECT_ATTBONUS_ASSASSIN,
	AFFECT_ATTBONUS_SURA,
	AFFECT_ATTBONUS_SHAMAN,
	AFFECT_POISON_PCT,
	AFFECT_PENETRATE_PCT,		// 240
	AFFECT_CRITICAL_PCT,
	AFFECT_ATTBONUS_MONSTER,	// 242
	AFFECT_BOSSHUNT_ATTSPEED,

	AFFECT_PREMIUM_START	= 500,
	AFFECT_EXP_BONUS		= 500,	// °æÇèÀÇ ¹ÝÁö
	AFFECT_ITEM_BONUS		= 501,	// µµµÏÀÇ Àå°©
	AFFECT_SAFEBOX		= 502,  // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT		= 503,	// PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND		= 504,	// PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST	= 505,	// ¿ø¾ÓÀÇ ±êÅÐ
	AFFECT_GOLD_BONUS		= 506,	// µ· µå·ÓÈ®·ü 50%Áõ°¡
	AFFECT_PREMIUM_END		= 509,

	AFFECT_MALL			= 510,	// ¸ô ¾ÆÀÌÅÛ ¿¡ÆåÆ®
	AFFECT_NO_DEATH_PENALTY	= 511,	// ¿ë½ÅÀÇ °¡È£ (°æÇèÄ¡°¡ ÆÐ³ÎÆ¼¸¦ ÇÑ¹ø ¸·¾ÆÁØ´Ù)
	AFFECT_SKILL_BOOK_BONUS	= 512,	// ¼±ÀÎÀÇ ±³ÈÆ (Ã¥ ¼ö·Ã ¼º°ø È®·üÀÌ 50% Áõ°¡)
	AFFECT_SKILL_NO_BOOK_DELAY	= 513,	// ÁÖ¾È¼ú¼­

	AFFECT_HAIR	= 514,	// Çì¾î È¿°ú
	AFFECT_COLLECT = 515, //¼öÁýÄù½ºÆ® 
	AFFECT_EXP_BONUS_EURO_FREE = 516, // °æÇèÀÇ ¹ÝÁö (À¯·´ ¹öÀü 14 ·¹º§ ÀÌÇÏ ±âº» È¿°ú)
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

#ifdef COMBAT_ZONE
	AFFECT_COMBAT_ZONE_POTION	= 519,
	AFFECT_COMBAT_ZONE_DEFENSE	= 520,
	AFFECT_COMBAT_ZONE_MOVEMENT	= 521,
#endif
	AFFECT_SKILL_NO_BOOK_DELAY2 = 522,
	AFFECT_SKILL_BOOK_BONUS2 = 523,

#ifdef __DRAGONSOUL__
	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,
#endif

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,
	
	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	AFFECT_MOVE_THROUGH_MONSTER = 536,

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING	   = 301,

	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,
	
	AFFECT_RAMADAN1 = 304,
	AFFECT_RAMADAN2 = 305,

	AFFECT_TEMPORARY_START = 600,
#ifdef __VOTE4BUFF__
	AFFECT_VOTE4BUFF = 600,
#endif
	AFFECT_ALIGNMENT_GOOD = 601,
	AFFECT_ALIGNMENT_BAD = 602,
#ifdef ENABLE_HYDRA_DUNGEON
	AFFECT_HYDRA = 603,
#endif
#ifdef ENABLE_RUNE_SYSTEM
	AFFECT_RUNE_MOVEMENT_SLOW = 604,
	AFFECT_RUNE_ATTACK_SLOW = 605,
	AFFECT_RUNE_MOUNT_PARALYZE = 606,
#endif
	AFFECT_TEMPORARY_END = 699,
	AFFECT_ANNIVERSARY_EVENT = 701,
	
	AFFECT_BIOLOGIST_START = 740,
	AFFECT_BIOLOGIST_END = 	AFFECT_BIOLOGIST_START + 20,
	
	AFFECT_EVENT_START = AFFECT_BIOLOGIST_END + 1,
	AFFECT_EVENT_END = 	AFFECT_EVENT_START + 18,

#ifdef __MELEY_LAIR_DUNGEON__
	AFFECT_STATUE = 800,
#endif
	AFFECT_AURA_START = 801,
	AFFECT_AURA_END = 900,

#ifdef ENABLE_RUNE_AFFECT_ICONS
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_1 = 901,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_2,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_3,

	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_13,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_14,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_15,

	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_25,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_26,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_27,

	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_37,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_38,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_39,

	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_49,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_50,
	AFFECT_RUNE_PRIMARY_SUBGROUP_KEY_51,
#endif

	AFFECT_QUEST_START_IDX = 1000,
};

enum EAffectBits
{   
	AFF_NONE,

	AFF_GAMEMASTER,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY,		// ´øÀü¿¡¼­ ÁØºñ »óÅÂ
	AFF_DUNGEON_UNIQUE,		// ´øÀü À¯´ÏÅ© (Å¬¶óÀÌ¾ðÆ®¿¡¼­ ÄÃ¸µµÇÁö¾ÊÀ½)

	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,

	AFF_JEONGWIHON,		// Àü±ÍÈ¥
	AFF_GEOMGYEONG,		// °Ë°æ
	AFF_GEOMGYEONG_PERFECT,
	AFF_CHEONGEUN,		// Ãµ±ÙÃß
	AFF_CHEONGEUN_PERFECT,
	AFF_GYEONGGONG,		// °æ°ø¼ú
	AFF_EUNHYUNG,		// ÀºÇü¹ý
	AFF_GWIGUM,			// ±Í°Ë
	AFF_GWIGUM_PERFECT,
	AFF_TERROR,			// °øÆ÷
	AFF_TERROR_PERFECT,
	AFF_JUMAGAP,		// ÁÖ¸¶°©
	AFF_HOSIN,			// È£½Å
	AFF_HOSIN_PERFECT,
	AFF_BOHO,			// º¸È£
	AFF_KWAESOK,		// Äè¼Ó
	AFF_MANASHIELD,		// ¸¶³ª½¯µå
	AFF_MANASHIELD_PERFECT,
	AFF_MUYEONG,		// ¹«¿µÁø affect
	AFF_REVIVE_INVISIBLE,	// ºÎÈ°½Ã Àá½Ãµ¿¾È ¹«Àû
	AFF_FIRE,			// Áö¼Ó ºÒ µ¥¹ÌÁö
	AFF_GICHEON,		// ±âÃµ´ë°ø
	AFF_GICHEON_PERFECT,
	AFF_JEUNGRYEOK,
	AFF_TANHWAN_DASH,		// ÅºÈ¯°Ý¿ë ´Þ¸®±â¾îÆåÆ®
	AFF_PABEOP,			// ÆÄ¹ý¼ú
	AFF_CHEONGEUN_WITH_FALL,	// Ãµ±ÙÃß
	AFF_POLYMORPH,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,

	AFF_CHINA_FIREWORK,

#ifdef __WOLFMAN__
	AFF_BLEEDING,
	AFF_RED_POSSESSION,
	AFF_BLUE_POSSESSION,
#endif

	AFF_MOVE_THROUGH_MONSTER,

#ifdef __MELEY_LAIR_DUNGEON__
	AFF_STATUE1,
	AFF_STATUE2,
	AFF_STATUE3,
	AFF_STATUE4,
#endif

#ifdef ENABLE_HYDRA_DUNGEON
	AFF_HYDRA,
#endif

#ifdef AUCTION_SYSTEM
	AFFECT_AUCTION_SHOP_OWNER,
#endif

#ifdef ENABLE_RUNE_SYSTEM
	AFF_MOUNT_PARALYZE,
#endif

	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Affect°¡ ¹«ÇÑ´ë·Î µé¾î°¡ ÀÖ¾î¾ß ÇÒ °æ¿ì »ç¿ë.
	// ½Ã°£À» °è¼Ó ÁÙÀÌ±â ¶§¹®¿¡ ¸Å¿ì Å«°ªÀ¸·Î ¹«ÇÑ´ë¸¦ ¿¡¹Ä·¹ÀÌ¼ÇÇÔ.
	//// 24ºñÆ®´Â ÀûÀ¸¹Ç·Î 25ºñÆ®¸¦ »ç¿ë.
	// ... 25ºñÆ® »ç¿ëÇÑ´Ù°í ÇØ³õ°í¼± 29bit »ç¿ëÇÏ°í ÀÖ´Â ¾öÃ»³­ ÁÖ¼®ÀÌ¶õ...
	// collect quest¿¡¼­ ¹«ÇÑ ½Ã°£À» 60³âÀ¸·Î »ç¿ëÇÏ°í ÀÖÀ¸¹Ç·Î, ¿©±âµµ 60³âÀ¸·Î ÇÏÀÚ.

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif
