#pragma once

#ifdef ENABLE_64BIT_MODE
#define LONG long long
#define ULONG unsigned long long
#define time_t __time64_t
#else
#define LONG long
#define ULONG unsigned long
#endif

typedef BYTE TPacketHeader;

enum
{
	HEADER_CG_CHAT                            = 40,
	HEADER_CG_PLAYER_CREATE                   = 85,
	HEADER_CG_PLAYER_DESTROY                  = 44,
	HEADER_CG_PLAYER_SELECT                   = 103,
	HEADER_CG_CHARACTER_MOVE                  = 78,
	HEADER_CG_SYNC_POSITION                   = 51,
	HEADER_CG_ENTERGAME                       = 76,
	HEADER_CG_ITEM_USE                        = 45,
	HEADER_CG_ITEM_DROP                       = 30,
	HEADER_CG_ITEM_MOVE                       = 37,
	HEADER_CG_ITEM_PICKUP                     = 27,
	HEADER_CG_QUICKSLOT_ADD                   = 88,
	HEADER_CG_QUICKSLOT_DEL                   = 18,
	HEADER_CG_QUICKSLOT_SWAP                  = 82,
	HEADER_CG_WHISPER                         = 46,
	HEADER_CG_ITEM_DROP2                      = 2,
	HEADER_CG_ON_CLICK                        = 50,
	HEADER_CG_EXCHANGE                        = 72,
	HEADER_CG_SCRIPT_ANSWER                   = 11,
	HEADER_CG_QUEST_INPUT_STRING              = 38,
	HEADER_CG_QUEST_CONFIRM                   = 39,
	HEADER_CG_SHOP                            = 58,
	HEADER_CG_FLY_TARGETING                   = 3,
	HEADER_CG_USE_SKILL                       = 56,
	HEADER_CG_ADD_FLY_TARGETING               = 101,
	HEADER_CG_SHOOT                           = 28,
	HEADER_CG_MYSHOP                          = 26,
	HEADER_CG_ITEM_USE_TO_ITEM                = 97,
	HEADER_CG_TARGET                          = 74,
	HEADER_CG_WARP                            = 75,
	HEADER_CG_SCRIPT_BUTTON                   = 10,
	HEADER_CG_MESSENGER                       = 13,
	HEADER_CG_MALL_CHECKOUT                   = 71,
	HEADER_CG_SAFEBOX_CHECKIN                 = 14,
	HEADER_CG_SAFEBOX_CHECKOUT                = 66,
	HEADER_CG_PARTY_INVITE                    = 12,
	HEADER_CG_PARTY_INVITE_ANSWER             = 104,
	HEADER_CG_PARTY_REMOVE                    = 89,
	HEADER_CG_PARTY_SET_STATE                 = 48,
	HEADER_CG_PARTY_USE_SKILL                 = 31,
	HEADER_CG_SAFEBOX_ITEM_MOVE               = 87,
	HEADER_CG_PARTY_PARAMETER                 = 25,
	HEADER_CG_GUILD                           = 57,
	HEADER_CG_ANSWER_MAKE_GUILD               = 15,
	HEADER_CG_FISHING                         = 32,
	HEADER_CG_GIVE_ITEM                       = 60,
	HEADER_CG_EMPIRE                          = 8,
	HEADER_CG_REFINE                          = 86,
	HEADER_CG_MARK_LOGIN                      = 92,
	HEADER_CG_MARK_CRCLIST                    = 100,
	HEADER_CG_MARK_UPLOAD                     = 29,
	HEADER_CG_MARK_IDXLIST                    = 47,
	HEADER_CG_HACK                            = 90,
	HEADER_CG_CHANGE_NAME                     = 36,
	HEADER_CG_LOGIN2                          = 20,
	HEADER_CG_LOGIN3                          = 7,
	HEADER_CG_GUILD_SYMBOL_UPLOAD             = 79,
	HEADER_CG_GUILD_SYMBOL_CRC                = 4,
	HEADER_CG_SCRIPT_SELECT_ITEM              = 95,
	HEADER_CG_ATTACK                          = 17,

#ifdef ENABLE_IPV6_FIX
	HEADER_CG_IPV6_FIX_ENABLE                 = 61,
#endif

	HEADER_CG_LOGIN_VERSION_CHECK			  = 69,

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	HEADER_CG_ACCE                            = 34,
#endif

#ifdef ENABLE_GUILD_SAFEBOX
	HEADER_CG_GUILD_SAFEBOX_OPEN              = 91,
	HEADER_CG_GUILD_SAFEBOX_CHECKIN           = 93,
	HEADER_CG_GUILD_SAFEBOX_CHECKOUT          = 102,
	HEADER_CG_GUILD_SAFEBOX_ITEM_MOVE         = 77,
	HEADER_CG_GUILD_SAFEBOX_GIVE_GOLD         = 80,
	HEADER_CG_GUILD_SAFEBOX_GET_GOLD          = 55,
#endif

	HEADER_CG_ITEM_DESTROY                    = 62,

#ifdef ENABLE_DRAGONSOUL
	HEADER_CG_DRAGON_SOUL_REFINE              = 98,
#endif

	HEADER_CG_TARGET_MONSTER_INFO             = 68,

	HEADER_CG_PLAYER_INFORMATION              = 6,
	HEADER_CG_ITEM_MULTI_USE                  = 105,

#ifdef ENABLE_PYTHON_REPORT_PACKET
	HEADER_CG_BOT_REPORT_LOG                  = 73,
#endif

	HEADER_CG_FORCED_REWARP                   = 63,
	HEADER_CG_DETACH_SINGLE                   = 24,

#ifdef ENABLE_HAIR_SELECTOR
	HEADER_CG_PLAYER_SELECT_HAIR              = 49,
#endif

#ifdef ENABLE_EVENT_SYSTEM
	HEADER_CG_EVENT_REQUEST_ANSWER            = 43,
#endif

#ifdef ENABLE_COSTUME_BONUS_TRANSFER
	HEADER_CG_COSTUME_BONUS_TRANSFER          = 33,
#endif

#ifdef COMBAT_ZONE
	HEADER_CG_COMBAT_ZONE_REQUEST_ACTION      = 53,
#endif

#ifdef ENABLE_RUNE_SYSTEM
	HEADER_CG_RUNE_PAGE                       = 23,
#endif

	HEADER_CG_HIT_SPACEBAR                    = 41,
	HEADER_CG_QUEST_TRIGGER                   = 9,

#ifdef CHANGE_SKILL_COLOR
	HEADER_CG_SKILL_COLOR                     = 42,
#endif

#ifdef INGAME_WIKI
	HEADER_CG_WIKI                            = 83,
#endif

#ifdef ENABLE_EQUIPMENT_CHANGER
	HEADER_CG_EQUIPMENT_PAGE_ADD              = 52,
	HEADER_CG_EQUIPMENT_PAGE_DELETE           = 54,
	HEADER_CG_EQUIPMENT_PAGE_SELECT           = 22,
#endif

	HEADER_CG_PACKET_MAX					  = 106, // editif you add new packets

	HEADER_CG_KEY_AGREEMENT					  = 0xfb, // _IMPROVED_PACKET_ENCRYPTION_
	HEADER_CG_TIME_SYNC						  = 0xfc,
	HEADER_CG_CLIENT_VERSION				  = 0xfd,
	HEADER_CG_CLIENT_VERSION2				  = 0xf1,
	HEADER_CG_PONG							  = 0xfe,
	HEADER_CG_HANDSHAKE						  = 0xff,
	/////////////////////////////////////////////////
	// From Server

	HEADER_GC_CHARACTER_ADD						= 1,
	HEADER_GC_CHARACTER_DEL						= 2,
	HEADER_GC_CHARACTER_MOVE					= 3,
	HEADER_GC_CHAT								= 4,
	HEADER_GC_SYNC_POSITION 					= 5,
	HEADER_GC_LOGIN_SUCCESS						= 6,
	HEADER_GC_LOGIN_FAILURE						= 7,
	HEADER_GC_PLAYER_CREATE_SUCCESS				= 8,
	HEADER_GC_PLAYER_CREATE_FAILURE				= 9,
	HEADER_GC_PLAYER_DELETE_SUCCESS				= 10,
	HEADER_GC_PLAYER_DELETE_WRONG_SOCIAL_ID		= 11,

	HEADER_GC_STUN								= 12,
	HEADER_GC_DEAD								= 13,

	HEADER_GC_MAIN_CHARACTER					= 14,
	HEADER_GC_PLAYER_POINTS						= 15,
	HEADER_GC_PLAYER_POINT_CHANGE				= 16,
	HEADER_GC_CHARACTER_UPDATE                  = 18,
	HEADER_GC_ITEM_DEL							= 19,
	HEADER_GC_ITEM_SET							= 20,
	HEADER_GC_ITEM_USE							= 21,
	HEADER_GC_ITEM_DROP							= 22,
	HEADER_GC_ITEM_UPDATE						= 23,
	HEADER_GC_ITEM_GROUND_ADD					= 24,
	HEADER_GC_ITEM_GROUND_DEL					= 25,
    HEADER_GC_QUICKSLOT_ADD                     = 26,
    HEADER_GC_QUICKSLOT_DEL                     = 27,
    HEADER_GC_QUICKSLOT_SWAP                    = 28,
	HEADER_GC_ITEM_OWNERSHIP					= 29,
	HEADER_GC_WHISPER							= 30,

	HEADER_GC_MOTION							= 31,

	HEADER_GC_SHOP							    = 32,
	HEADER_GC_SHOP_SIGN							= 33,

	HEADER_GC_DUEL_START						= 34,
	HEADER_GC_PVP								= 35,
	HEADER_GC_EXCHANGE							= 36,
    HEADER_GC_CHARACTER_POSITION                = 37,

	HEADER_GC_PING								= 38,

	HEADER_GC_SCRIPT							= 39,
    HEADER_GC_QUEST_CONFIRM                     = 40,

	HEADER_GC_OWNERSHIP                         = 42, 
    HEADER_GC_TARGET                            = 43,
	HEADER_GC_WARP								= 44, 
	HEADER_GC_ADD_FLY_TARGETING                 = 45,

	HEADER_GC_CREATE_FLY						= 46,
	HEADER_GC_FLY_TARGETING						= 47,
	HEADER_GC_SKILL_LEVEL						= 48,
    HEADER_GC_MESSENGER                         = 49,
	HEADER_GC_GUILD								= 50,

    HEADER_GC_PARTY_INVITE                      = 51,
    HEADER_GC_PARTY_ADD                         = 52,
    HEADER_GC_PARTY_UPDATE                      = 53,
    HEADER_GC_PARTY_REMOVE                      = 54,

    HEADER_GC_QUEST_INFO                        = 55,
    HEADER_GC_REQUEST_MAKE_GUILD                = 56,
	HEADER_GC_PARTY_PARAMETER                   = 57,

    HEADER_GC_SAFEBOX_SET                       = 58,
    HEADER_GC_SAFEBOX_DEL                       = 59,
    HEADER_GC_SAFEBOX_WRONG_PASSWORD            = 60,
    HEADER_GC_SAFEBOX_SIZE                      = 61,

    HEADER_GC_FISHING                           = 62,

    HEADER_GC_EMPIRE                            = 63,

    HEADER_GC_PARTY_LINK                        = 64,
    HEADER_GC_PARTY_UNLINK                      = 65,

    HEADER_GC_REFINE_INFORMATION                = 66,

	HEADER_GC_OBSERVER_ADD						= 67,
	HEADER_GC_OBSERVER_REMOVE					= 68,
	HEADER_GC_OBSERVER_MOVE						= 69,
	HEADER_GC_VIEW_EQUIP                        = 70,

	HEADER_GC_MARK_BLOCK						= 71,
	HEADER_GC_MARK_IDXLIST						= 72,

    HEADER_GC_TIME                              = 73,
    HEADER_GC_CHANGE_NAME                       = 74,

	HEADER_GC_DUNGEON							= 75,
	HEADER_GC_WALK_MODE							= 76, 
	HEADER_GC_CHANGE_SKILL_GROUP				= 77,

    HEADER_GC_SEPCIAL_EFFECT                    = 78,
	HEADER_GC_NPC_POSITION						= 79,

    HEADER_GC_LOGIN_KEY                         = 81,

	HEADER_GC_TARGET_UPDATE                     = 83,
	HEADER_GC_TARGET_DELETE                     = 84,
	HEADER_GC_TARGET_CREATE						= 85,

	HEADER_GC_AFFECT_ADD                        = 86,
	HEADER_GC_AFFECT_REMOVE                     = 87,
	
    HEADER_GC_MALL_OPEN                         = 88,
    HEADER_GC_MALL_SET                          = 89,
    HEADER_GC_MALL_DEL                          = 90,

	HEADER_GC_LAND_LIST                         = 91,
	HEADER_GC_LOVER_INFO						= 92,
	HEADER_GC_LOVE_POINT_UPDATE					= 93,
	HEADER_GC_GUILD_SYMBOL_DATA					= 94,
    HEADER_GC_DIG_MOTION                        = 95,

	HEADER_GC_DAMAGE_INFO						= 96,
	HEADER_GC_CHAR_ADDITIONAL_INFO				= 97,

    HEADER_GC_AUTH_SUCCESS                      = 98,
	HEADER_GC_SPECIFIC_EFFECT					= 107,

	HEADER_GC_DISABLE_OUTPUT_BUFFER				= 108,

	HEADER_GC_PVP_TEAM_SET						= 109,

	HEADER_GC_LOGIN_VERSION_ANSWER				= 110,

	HEADER_GC_CLEAR_OUTPUT_BUFFER				= 111,

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	HEADER_GC_ACCE								= 112,
#endif

#ifdef ENABLE_MAINTENANCE
	HEADER_GC_MAINTENANCE						= 113,
#endif

#ifdef ENABLE_GUILD_SAFEBOX
	HEADER_GC_GUILD_SAFEBOX						= 114,
#endif

	HEADER_GC_INVENTORY_MAX_NUM					= 115,

#ifdef ENABLE_ATTRIBUTES_TO_CLIENT
	HEADER_GC_ATTRIBUTES_TO_CLIENT				= 120,
#endif

	HEADER_GC_PLAYER_REAL_POINT_SET				= 121,

#ifdef ENABLE_DRAGONSOUL
	HEADER_GC_DRAGON_SOUL_REFINE				= 122,
#endif

	HEADER_GC_HORSE_REFINE_INFO					= 123,
	HEADER_GC_HORSE_REFINE_RESULT				= 124,

#ifdef ENABLE_GAYA_SYSTEM
	HEADER_GC_GAYA_SHOP_OPEN					= 125,
#endif

	HEADER_GC_TARGET_MONSTER_DROP_INFO			= 126,

	HEADER_GC_SHOW_TEAMLER						= 128,
	HEADER_GC_TEAMLER_STATUS					= 129,
	HEADER_GC_PLAYER_INFORMATION				= 130,
	HEADER_GC_SKILL_MOTION						= 131,
	
#ifdef ENABLE_FAKEBUFF
	HEADER_GC_FAKE_BUFF_SKILL = 132,
#endif

	HEADER_GC_QUEST_DELETE = 133,

#ifdef ENABLE_ATTRTREE
	HEADER_GC_ATTRTREE_LEVEL = 134,
	HEADER_GC_ATTRTREE_REFINE = 135,
#endif

#ifdef ENABLE_EVENT_SYSTEM
	HEADER_GC_EVENT_REQUEST = 136,
	HEADER_GC_EVENT_CANCEL = 137,
	HEADER_GC_EVENT_EMPIREWAR_LOAD = 138,
	HEADER_GC_EVENT_EMPIREWAR_UPDATE = 139,
	HEADER_GC_EVENT_EMPIREWAR_FINISH = 140,
#endif
	
#ifdef ENABLE_COSTUME_BONUS_TRANSFER
	HEADER_GC_COSTUME_BONUS_TRANSFER = 141,
#endif

#ifdef COMBAT_ZONE
	HEADER_GC_RANKING_COMBAT_ZONE = 142,
	HEADER_GC_SEND_COMBAT_ZONE = 143,
#endif

	HEADER_GC_SHINING = 144,

#ifdef ENABLE_RUNE_SYSTEM
	HEADER_GC_RUNE = 145,
	HEADER_GC_RUNE_PAGE = 146,
	HEADER_GC_RUNE_REFINE = 147,
	HEADER_GC_RUNE_RESET_OWNED = 148,
#ifdef ENABLE_LEVEL2_RUNES
	HEADER_GC_RUNE_LEVELUP = 149,
#endif
#endif

	HEADER_GC_SOUL_REFINE_INFO = 150,

#ifdef INGAME_WIKI
	HEADER_GC_WIKI = 151,
	HEADER_GC_WIKI_MOB = 152,
#endif


#ifdef ENABLE_EQUIPMENT_CHANGER
	HEADER_GC_EQUIPMENT_PAGE_LOAD = 153,
#endif

#ifdef DMG_METER
	HEADER_GC_DMG_METER = 154,
#endif

#ifdef BATTLEPASS_EXTENSION
		HEADER_GC_BATTLEPASS_DATA = 155,
#endif

#ifdef ENABLE_ANIMAL_SYSTEM
		HEADER_GC_ANIMAL_SUMMON = 156,
		HEADER_GC_ANIMAL_UPDATE_LEVEL = 157,
		HEADER_GC_ANIMAL_UPDATE_EXP = 158,
		HEADER_GC_ANIMAL_UPDATE_STATS = 159,
		HEADER_GC_ANIMAL_UNSUMMON = 160,
#endif

	HEADER_GC_KEY_AGREEMENT_COMPLETED			= 0xfa, // _IMPROVED_PACKET_ENCRYPTION_
	HEADER_GC_KEY_AGREEMENT						= 0xfb, // _IMPROVED_PACKET_ENCRYPTION_
	HEADER_GC_HANDSHAKE_OK						= 0xfc, // 252
	HEADER_GC_PHASE								= 0xfd,	// 253
    HEADER_GC_BINDUDP                           = 0xfe, // 254
    HEADER_GC_HANDSHAKE                         = 0xff, // 255
};

#ifndef PACKET_H_ONLY_PACKET_HEADERS

#include "Locale_m2.h"
#include "../gamelib/RaceData.h"

enum
{
	ID_MAX_NUM = 30,
	PASS_MAX_NUM = 16,
	HWID_MAX_NUM = 32,
	CHAT_MAX_NUM = 128,
	PATH_NODE_MAX_NUM = 64,
	SHOP_SIGN_MAX_LEN = 32,

	PLAYER_PER_ACCOUNT3 = 3,
	PLAYER_PER_ACCOUNT4 = 4,

	PLAYER_ITEM_SLOT_MAX_NUM = 20,		// 플래이어의 슬롯당 들어가는 갯수.

	QUICKSLOT_MAX_LINE = 4,
	QUICKSLOT_MAX_COUNT_PER_LINE = 8, // 클라이언트 임의 결정값
	QUICKSLOT_MAX_COUNT = QUICKSLOT_MAX_LINE * QUICKSLOT_MAX_COUNT_PER_LINE,

	QUICKSLOT_MAX_NUM = 36, // 서버와 맞춰져 있는 값

	SHOP_HOST_ITEM_MAX_NUM = 40,

	METIN_SOCKET_COUNT = 6,

	PARTY_AFFECT_SLOT_MAX_NUM = 7,

	GUILD_GRADE_NAME_MAX_LEN = 16,
	GUILD_NAME_MAX_LEN = 35,
	GUILD_GRADE_COUNT = 15,
	GULID_COMMENT_MAX_LEN = 50,

	MARK_CRC_NUM = 8*8,
	MARK_DATA_SIZE = 16*12,
	SYMBOL_DATA_SIZE = 128*256,
	QUEST_INPUT_STRING_MAX_NUM = 64,

	PRIVATE_CODE_LENGTH = 8,

	REFINE_MATERIAL_MAX_NUM = 5,

	WEAR_MAX_NUM = 11,

	SHOP_TAB_NAME_MAX = 32,
	SHOP_TAB_COUNT_MAX = 3,
};

enum EBattleMode
{
	BATTLEMODE_ATTACK = 0,
	BATTLEMODE_DEFENSE = 1,
};

enum
{
    SHOP_SUBHEADER_CG_END,
	SHOP_SUBHEADER_CG_BUY,
	SHOP_SUBHEADER_CG_SELL,
	SHOP_SUBHEADER_CG_SELL2,
};

enum
{
	EXCHANGE_SUBHEADER_CG_START,			// arg1 == vid of target character
	EXCHANGE_SUBHEADER_CG_ITEM_ADD,		// arg1 == position of item
	EXCHANGE_SUBHEADER_CG_ITEM_DEL,		// arg1 == position of item
	EXCHANGE_SUBHEADER_CG_ELK_ADD,			// arg1 == amount of elk
	EXCHANGE_SUBHEADER_CG_ACCEPT,			// arg1 == not used
	EXCHANGE_SUBHEADER_CG_CANCEL,			// arg1 == not used
};

enum
{
#ifdef ENABLE_MESSENGER_BLOCK
	MESSENGER_SUBHEADER_GC_BLOCK_LIST,
	MESSENGER_SUBHEADER_GC_BLOCK_LOGIN,
	MESSENGER_SUBHEADER_GC_BLOCK_LOGOUT,
	MESSENGER_SUBHEADER_GC_BLOCK_INVITE,//not used
#endif	
	MESSENGER_SUBHEADER_GC_LIST,
	MESSENGER_SUBHEADER_GC_LOGIN,
	MESSENGER_SUBHEADER_GC_LOGOUT,
	MESSENGER_SUBHEADER_GC_INVITE,
	MESSENGER_SUBHEADER_GC_MOBILE,
};

enum
{
	MESSENGER_CONNECTED_STATE_OFFLINE,
	MESSENGER_CONNECTED_STATE_ONLINE,
	MESSENGER_CONNECTED_STATE_MOBILE,
};

enum
{
#ifdef ENABLE_MESSENGER_BLOCK
	MESSENGER_SUBHEADER_CG_ADD_BLOCK_BY_VID,
    MESSENGER_SUBHEADER_CG_ADD_BLOCK_BY_NAME,
    MESSENGER_SUBHEADER_CG_REMOVE_BLOCK,
#endif
	MESSENGER_SUBHEADER_CG_ADD_BY_VID,
    MESSENGER_SUBHEADER_CG_ADD_BY_NAME,
    MESSENGER_SUBHEADER_CG_REMOVE,
};

enum
{
	SAFEBOX_MONEY_STATE_SAVE,
	SAFEBOX_MONEY_STATE_WITHDRAW,
};

enum
{
	GUILD_SUBHEADER_CG_ADD_MEMBER,
	GUILD_SUBHEADER_CG_REMOVE_MEMBER,
	GUILD_SUBHEADER_CG_CHANGE_GRADE_NAME,
	GUILD_SUBHEADER_CG_CHANGE_GRADE_AUTHORITY,
	GUILD_SUBHEADER_CG_OFFER,
	GUILD_SUBHEADER_CG_POST_COMMENT,
	GUILD_SUBHEADER_CG_DELETE_COMMENT,
	GUILD_SUBHEADER_CG_REFRESH_COMMENT,
	GUILD_SUBHEADER_CG_CHANGE_MEMBER_GRADE,
	GUILD_SUBHEADER_CG_USE_SKILL,
	GUILD_SUBHEADER_CG_CHANGE_MEMBER_GENERAL,
	GUILD_SUBHEADER_CG_GUILD_INVITE_ANSWER,
	GUILD_SUBHEADER_CG_CHARGE_GSP,
	GUILD_SUBHEADER_CG_DEPOSIT_MONEY,
	GUILD_SUBHEADER_CG_WITHDRAW_MONEY,
	GUILD_SUBHEADER_CG_REQUEST_GUILD_LIST,
	GUILD_SUBHEADER_CG_SEARCH_GUILD,
};

struct guildLadder
{
	char name[GUILD_NAME_MAX_LEN + 1];
	BYTE level;
	DWORD ladderPoints;
	BYTE minMember;
	BYTE maxMember;
};

enum EPartyExpDistributionType
{
    PARTY_EXP_DISTRIBUTION_NON_PARITY,
    PARTY_EXP_DISTRIBUTION_PARITY,
};

#define	SKILL_MAX_NUM 255

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// From Server
enum EPhase
{
    PHASE_CLOSE,				// 끊기는 상태 (또는 끊기 전 상태)
    PHASE_HANDSHAKE,			// 악수..;;
    PHASE_LOGIN,				// 로그인 중
    PHASE_SELECT,				// 캐릭터 선택 화면
    PHASE_LOADING,				// 선택 후 로딩 화면
    PHASE_GAME,					// 게임 화면
    PHASE_DEAD,					// 죽었을 때.. (게임 안에 있는 것일 수도..)

	PHASE_DBCLIENT_CONNECTING,	// 서버용
    PHASE_DBCLIENT,				// 서버용
    PHASE_P2P,					// 서버용
    PHASE_AUTH,					// 로그인 인증 용
};

enum { LOGIN_STATUS_MAX_LEN = 8 };

enum
{
	ADD_CHARACTER_STATE_DEAD   = (1 << 0),
	ADD_CHARACTER_STATE_SPAWN  = (1 << 1),
	ADD_CHARACTER_STATE_GUNGON = (1 << 2),
	ADD_CHARACTER_STATE_KILLER = (1 << 3),
	ADD_CHARACTER_STATE_PARTY  = (1 << 4),
};

enum EPKModes
{
	PK_MODE_PEACE,
	PK_MODE_REVENGE,
	PK_MODE_FREE,
	PK_MODE_PROTECT,
	PK_MODE_GUILD,
	PK_MODE_MAX_NUM,
};

// 2004.11.20.myevan.CRaceData::PART_MAX_NUM 사용안하게 수정 - 서버에서 사용하는것과 일치하지 않음
enum ECharacterEquipmentPart
{
	CHR_EQUIPPART_ARMOR,
	CHR_EQUIPPART_WEAPON,
	CHR_EQUIPPART_HEAD,
	CHR_EQUIPPART_HAIR,
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	CHR_EQUIPPART_ACCE,
#endif

	CHR_EQUIPPART_NUM,		
};

enum EChatType
{
	CHAT_TYPE_TALKING,  /* 그냥 채팅 */
	CHAT_TYPE_INFO,     /* 정보 (아이템을 집었다, 경험치를 얻었다. 등) */
	CHAT_TYPE_NOTICE,   /* 공지사항 */
	CHAT_TYPE_PARTY,    /* 파티말 */
	CHAT_TYPE_GUILD,    /* 길드말 */
	CHAT_TYPE_COMMAND,	/* 명령 */
	CHAT_TYPE_SHOUT,	/* 외치기 */
	CHAT_TYPE_TEAM,
	CHAT_TYPE_WHISPER,	// 서버와는 연동되지 않는 Only Client Enum
	CHAT_TYPE_BIG_NOTICE,
#ifdef ENABLE_ZODIAC
	CHAT_TYPE_ZODIAC_NOTICE,
#endif
	CHAT_TYPE_MAX_NUM,
};

#ifdef COMBAT_ZONE
enum EPacketCGCombatZoneSubHeaderType
{
	COMBAT_ZONE_SUB_HEADER_NONE,
	COMBAT_ZONE_SUB_HEADER_ADD_LEAVING_TARGET,
	COMBAT_ZONE_SUB_HEADER_REMOVE_LEAVING_TARGET,
	COMBAT_ZONE_SUB_HEADER_FLASH_ON_MINIMAP,
	COMBAT_ZONE_SUB_HEADER_OPEN_RANKING,
	COMBAT_ZONE_SUB_HEADER_REFRESH_SHOP,
};
#endif

enum EPointTypes
{
    POINT_NONE,                 // 0
    POINT_LEVEL,                // 1
    POINT_VOICE,                // 2
    POINT_EXP,                  // 3
    POINT_NEXT_EXP,             // 4
    POINT_HP,                   // 5
    POINT_MAX_HP,               // 6
    POINT_SP,                   // 7
    POINT_MAX_SP,               // 8  
    POINT_STAMINA,              // 9  스테미너
    POINT_MAX_STAMINA,          // 10 최대 스테미너
    
    POINT_GOLD,                 // 11
    POINT_ST,                   // 12 근력
    POINT_HT,                   // 13 체력
    POINT_DX,                   // 14 민첩성
    POINT_IQ,                   // 15 정신력
    POINT_ATT_POWER,            // 16 공격력
    POINT_ATT_SPEED,            // 17 공격속도
    POINT_EVADE_RATE,           // 18 회피율
    POINT_MOV_SPEED,            // 19 이동속도
    POINT_DEF_GRADE,            // 20 방어등급
	POINT_CASTING_SPEED,        // 21 주문속도 (쿨다운타임*100) / (100 + 이값) = 최종 쿨다운 타임
	POINT_MAGIC_ATT_GRADE,      // 22 마법공격력
    POINT_MAGIC_DEF_GRADE,      // 23 마법방어력
    POINT_EMPIRE_POINT,         // 24 제국점수
    POINT_LEVEL_STEP,           // 25 한 레벨에서의 단계.. (1 2 3 될 때 보상, 4 되면 레벨 업)
    POINT_STAT,                 // 26 능력치 올릴 수 있는 개수
	POINT_SUB_SKILL,            // 27 보조 스킬 포인트
	POINT_SKILL,                // 28 액티브 스킬 포인트
//    POINT_SKILL_PASV,           // 27 패시브 기술 올릴 수 있는 개수
//    POINT_SKILL_ACTIVE,         // 28 액티브 스킬 포인트
	POINT_MIN_ATK,				// 29 최소 파괴력
	POINT_MAX_ATK,				// 30 최대 파괴력
    POINT_PLAYTIME,             // 31 플레이시간
    POINT_HP_REGEN,             // 32 HP 회복률
    POINT_SP_REGEN,             // 33 SP 회복률
    
    POINT_BOW_DISTANCE,         // 34 활 사정거리 증가치 (meter)
    
    POINT_HP_RECOVERY,          // 35 체력 회복 증가량
    POINT_SP_RECOVERY,          // 36 정신력 회복 증가량
    
    POINT_POISON_PCT,           // 37 독 확률
    POINT_STUN_PCT,             // 38 기절 확률
    POINT_SLOW_PCT,             // 39 슬로우 확률
    POINT_CRITICAL_PCT,         // 40 크리티컬 확률
    POINT_PENETRATE_PCT,        // 41 관통타격 확률
    POINT_CURSE_PCT,            // 42 저주 확률
    
    POINT_ATTBONUS_HUMAN,       // 43 인간에게 강함
    POINT_ATTBONUS_ANIMAL,      // 44 동물에게 데미지 % 증가
    POINT_ATTBONUS_ORC,         // 45 웅귀에게 데미지 % 증가
    POINT_ATTBONUS_MILGYO,      // 46 밀교에게 데미지 % 증가
    POINT_ATTBONUS_UNDEAD,      // 47 시체에게 데미지 % 증가
    POINT_ATTBONUS_DEVIL,       // 48 마귀(악마)에게 데미지 % 증가
    POINT_ATTBONUS_INSECT,      // 49 벌레족
    POINT_ATTBONUS_FIRE,        // 50 화염족
    POINT_ATTBONUS_ICE,         // 51 빙설족
    POINT_ATTBONUS_DESERT,      // 52 사막족
	POINT_ATTBONUS_MONSTER,	 // 55 ¸ðμc ¸o½ºAI¿¡°O °­CO
	POINT_ATTBONUS_WARRIOR,	 // 56 ¹≪≫c¿¡°O °­CO
	POINT_ATTBONUS_ASSASSIN,	// 57 AU°´¿¡°O °­CO
	POINT_ATTBONUS_SURA,		// 58 ¼o¶o¿¡°O °­CO
	POINT_ATTBONUS_SHAMAN,		// 59 ¹≪´c¿¡°O °­CO
	POINT_ATTBONUS_TREE,	 	// 60 ³ª¹≪¿¡°O °­CO 20050729.myevan UNUSED5 

	POINT_RESIST_WARRIOR,		// 59 무사에게 저항
	POINT_RESIST_ASSASSIN,		// 60 자객에게 저항
	POINT_RESIST_SURA,			// 61 수라에게 저항
	POINT_RESIST_SHAMAN,		// 62 무당에게 저항

    POINT_STEAL_HP,             // 63 생명력 흡수
    POINT_STEAL_SP,             // 64 정신력 흡수

    POINT_MANA_BURN_PCT,        // 65 마나 번

    /// 피해시 보너스 ///

    POINT_DAMAGE_SP_RECOVER,    // 66 공격당할 시 정신력 회복 확률

    POINT_BLOCK,                // 67 블럭율
    POINT_DODGE,                // 68 회피율

    POINT_RESIST_SWORD,         // 69
    POINT_RESIST_TWOHAND,       // 70
    POINT_RESIST_DAGGER,        // 71
    POINT_RESIST_BELL,          // 72
    POINT_RESIST_FAN,           // 73
    POINT_RESIST_BOW,           // 74  화살   저항   : 대미지 감소
    POINT_RESIST_FIRE,          // 75  화염   저항   : 화염공격에 대한 대미지 감소
    POINT_RESIST_ELEC,          // 76  전기   저항   : 전기공격에 대한 대미지 감소
    POINT_RESIST_MAGIC,         // 77  술법   저항   : 모든술법에 대한 대미지 감소
    POINT_RESIST_WIND,          // 78  바람   저항   : 바람공격에 대한 대미지 감소

    POINT_REFLECT_MELEE,        // 79 공격 반사

    /// 특수 피해시 ///
    POINT_REFLECT_CURSE,        // 80 저주 반사
    POINT_POISON_REDUCE,        // 81 독데미지 감소

    /// 적 소멸시 ///
    POINT_KILL_SP_RECOVER,      // 82 적 소멸시 MP 회복
    POINT_EXP_DOUBLE_BONUS,     // 83
    POINT_GOLD_DOUBLE_BONUS,    // 84
    POINT_ITEM_DROP_BONUS,      // 85

    /// 회복 관련 ///
    POINT_POTION_BONUS,         // 86
    POINT_KILL_HP_RECOVERY,      // 87

    POINT_IMMUNE_STUN,          // 88
    POINT_IMMUNE_SLOW,          // 89
    POINT_IMMUNE_FALL,          // 90
    //////////////////

    POINT_PARTY_ATT_GRADE,      // 91
    POINT_PARTY_DEF_GRADE,      // 92

    POINT_ATT_BONUS,            // 93
    POINT_DEF_BONUS,            // 94

    POINT_ATT_GRADE_BONUS,			// 95
    POINT_DEF_GRADE_BONUS,			// 96
    POINT_MAGIC_ATT_GRADE_BONUS,	// 97
    POINT_MAGIC_DEF_GRADE_BONUS,	// 98

    POINT_RESIST_NORMAL_DAMAGE,		// 99

	POINT_STAT_RESET_COUNT = 112,
    POINT_HORSE_SKILL = 113,

	POINT_MALL_ATTBONUS,		// 114 공격력 +x%
	POINT_MALL_DEFBONUS,		// 115 방어력 +x%
	POINT_MALL_EXPBONUS,		// 116 경험치 +x%
	POINT_MALL_ITEMBONUS,		// 117 아이템 드롭율 x/10배
	POINT_MALL_GOLDBONUS,		// 118 돈 드롭율 x/10배
    POINT_MAX_HP_PCT,			// 119 최대생명력 +x%
    POINT_MAX_SP_PCT,			// 120 최대정신력 +x%

	POINT_SKILL_DAMAGE_BONUS,       // 121 스킬 데미지 *(100+x)%
	POINT_NORMAL_HIT_DAMAGE_BONUS,  // 122 평타 데미지 *(100+x)%
   
    POINT_SKILL_DEFEND_BONUS,       // 123 스킬 방어 데미지
    POINT_NORMAL_HIT_DEFEND_BONUS,  // 124 평타 방어 데미지

	POINT_RAMADAN_CANDY_BONUS_EXP,	// 125

	POINT_ENERGY = 128,				// 128 기력

	// 기력 ui 용.
	// 이렇게 하고 싶지 않았지만, 
	// uiTaskBar에서는 affect에 접근할 수 없고,
	// 더구나 클라리언트에서는 blend_affect는 관리하지 않아,
	// 임시로 이렇게 둔다.
	POINT_ENERGY_END_TIME = 129,	// 129 기력 종료 시간

	POINT_COSTUME_ATTR_BONUS = 130,
	POINT_MAGIC_ATT_BONUS_PER = 131,
	POINT_MELEE_MAGIC_ATT_BONUS_PER = 132,

	// 추가 속성 저항
	POINT_RESIST_ICE = 133,          //   냉기 저항   : 얼음공격에 대한 대미지 감소
	POINT_RESIST_EARTH = 134,        //   대지 저항   : 얼음공격에 대한 대미지 감소
	POINT_RESIST_DARK = 135,         //   어둠 저항   : 얼음공격에 대한 대미지 감소

	POINT_RESIST_CRITICAL = 136,		// 크리티컬 저항	: 상대의 크리티컬 확률을 감소
	POINT_RESIST_PENETRATE = 137,		// 관통타격 저항	: 상대의 관통타격 확률을 감소

	POINT_EXP_REAL_BONUS = 138,		// exp real bonus 5 = 5 % 

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	POINT_ACCEDRAIN_RATE = 144,
#endif

#ifdef ENABLE_PET_SYSTEM
	POINT_PET_EXP_BONUS = 145,
#endif

	POINT_RESIST_MONSTER = 146,
	POINT_ATTBONUS_METIN = 147,
	POINT_ATTBONUS_BOSS = 148,

	POINT_ANTI_EXP = 149,

	POINT_RESIST_HUMAN = 150,

#ifdef ENABLE_ANIMAL_SYSTEM
	POINT_MOUNT_EXP_BONUS = 151,
#endif

	POINT_MOUNT_BUFF_BONUS = 152,

#ifdef ENABLE_GAYA_SYSTEM
	POINT_GAYA = 153,
#endif
	POINT_RESIST_SWORD_PEN,
	POINT_RESIST_TWOHAND_PEN,
	POINT_RESIST_DAGGER_PEN,
	POINT_RESIST_BELL_PEN,
	POINT_RESIST_FAN_PEN,
	POINT_RESIST_BOW_PEN,
	POINT_RESIST_ATTBONUS_HUMAN,

	// 클라이언트 포인트
// #ifdef __ELEMENT_SYSTEM__
		POINT_ATTBONUS_ELEC,
		POINT_ATTBONUS_WIND,
		POINT_ATTBONUS_EARTH,
		POINT_ATTBONUS_DARK,
// #endif

	POINT_ANTI_RESIST_MAGIC,
	POINT_BLOCK_IGNORE_BONUS,

	POINT_EMPIRE_A_KILLED,
	POINT_EMPIRE_B_KILLED,
	POINT_EMPIRE_C_KILLED,
	POINT_DUELS_WON,
	POINT_DUELS_LOST,
	POINT_MONSTERS_KILLED,
	POINT_BOSSES_KILLED,
	POINT_STONES_DESTROYED,
// #ifdef ENABLE_RUNE_SYSTEM
	POINT_RUNE_SHIELD_PER_HIT,
	POINT_RUNE_HEAL_ON_KILL,
	POINT_RUNE_BONUS_DAMAGE_AFTER_HIT,
	POINT_RUNE_3RD_ATTACK_BONUS,
	POINT_RUNE_FIRST_NORMAL_HIT_BONUS,
	POINT_RUNE_MSHIELD_PER_SKILL,
	POINT_RUNE_HARVEST,
	POINT_RUNE_DAMAGE_AFTER_3,
	POINT_RUNE_OUT_OF_COMBAT_SPEED,
	POINT_RUNE_RESET_SKILL,
	POINT_RUNE_COMBAT_CASTING_SPEED,
	POINT_RUNE_MAGIC_DAMAGE_AFTER_HIT,
	POINT_RUNE_MOVSPEED_AFTER_3,
	POINT_RUNE_SLOW_ON_ATTACK,
	POINT_RUNE_ATTACK_SLOW_PCT,
	POINT_RUNE_MOVEMENT_SLOW_PCT,
// #endif

	POINT_HEAL_EFFECT_BONUS,
	POINT_CRITICAL_DAMAGE_BONUS,
	POINT_DOUBLE_ITEM_DROP_BONUS,
	POINT_DAMAGE_BY_SP_BONUS,
	POINT_AURA_HEAL_EFFECT_BONUS,
	POINT_AURA_EQUIP_SKILL_BONUS,
	POINT_SINGLETARGET_SKILL_DAMAGE_BONUS,
	POINT_MULTITARGET_SKILL_DAMAGE_BONUS,
	POINT_MIXED_DEFEND_BONUS,
	POINT_EQUIP_SKILL_BONUS,

// #ifdef ENABLE_RUNE_SYSTEM
	POINT_RUNE_LEADERSHIP_BONUS,
	POINT_RUNE_MOUNT_PARALYZE,
	POINT_RUNE_CRITICAL_PVM,
// #endif

// #ifdef STANDARD_SKILL_DURATION
	POINT_SKILL_DURATION,
// #endif

	POINT_MIN_WEP = 200,
	POINT_MAX_WEP,
	POINT_MIN_MAGIC_WEP,
	POINT_MAX_MAGIC_WEP,
	POINT_HIT_RATE,

	POINT_ATTBONUS_ALL_ELEMENTS = 205,
// #ifdef ENABLE_ZODIAC
	POINT_ANIMASPHERE = 206,
	POINT_ATTBONUS_ZODIAC,
// #endif

	POINT_BONUS_UPGRADE_CHANCE, //APPLY_BONUS_UPGRADE_CHANCE
	POINT_LOWER_DUNGEON_CD, // APPLY_LOWER_DUNGEON_CD
	POINT_LOWER_BIOLOG_CD,

#ifdef ENABLE_WOLFMAN
		POINT_BLEEDING_PCT,
		POINT_BLEEDING_REDUCE,
		POINT_ATTBONUS_WOLFMAN,
		POINT_RESIST_WOLFMAN,
		POINT_RESIST_CLAW,
#endif

	POINT_RESIST_MAGIC_REDUCTION,
	
	POINT_RESIST_BOSS,
};

enum EPacketShopSubHeaders
{
	SHOP_SUBHEADER_GC_START,
    SHOP_SUBHEADER_GC_END,
	SHOP_SUBHEADER_GC_UPDATE_ITEM,
	SHOP_SUBHEADER_GC_UPDATE_PRICE,
    SHOP_SUBHEADER_GC_OK,
    SHOP_SUBHEADER_GC_NOT_ENOUGH_MONEY,
    SHOP_SUBHEADER_GC_SOLDOUT,
    SHOP_SUBHEADER_GC_INVENTORY_FULL,
    SHOP_SUBHEADER_GC_INVALID_POS,
	SHOP_SUBHEADER_GC_SOLD_OUT,
	SHOP_SUBHEADER_GC_START_EX,
	SHOP_SUBHEADER_GC_NOT_ENOUGH_MONEY_EX,
#ifdef COMBAT_ZONE
	SHOP_SUBHEADER_GC_NOT_ENOUGH_POINTS,
	SHOP_SUBHEADER_GC_MAX_LIMIT_POINTS,
	SHOP_SUBHEADER_GC_OVERFLOW_LIMIT_POINTS,
#endif
#ifdef ENABLE_ZODIAC
	SHOP_SUBHEADER_GC_ZODIAC_SHOP,
#endif
};

enum
{
    EXCHANGE_SUBHEADER_GC_START,			// arg1 == vid
    EXCHANGE_SUBHEADER_GC_ITEM_ADD,		// arg1 == vnum  arg2 == pos  arg3 == count
	EXCHANGE_SUBHEADER_GC_ITEM_DEL,		// arg1 == pos
    EXCHANGE_SUBHEADER_GC_ELK_ADD,			// arg1 == elk
    EXCHANGE_SUBHEADER_GC_ACCEPT,			// arg1 == accept
    EXCHANGE_SUBHEADER_GC_END,				// arg1 == not used
    EXCHANGE_SUBHEADER_GC_ALREADY,			// arg1 == not used
    EXCHANGE_SUBHEADER_GC_LESS_ELK,		// arg1 == not used
};

enum
{
	QUEST_SEND_IS_BEGIN         = 1 << 0,
    QUEST_SEND_TITLE            = 1 << 1,  // 28자 까지
    QUEST_SEND_CLOCK_NAME       = 1 << 2,  // 16자 까지
    QUEST_SEND_CLOCK_VALUE      = 1 << 3,
    QUEST_SEND_COUNTER			= 1 << 4,  // 16자 까지
	QUEST_SEND_ICON_FILE		= 1 << 5,  // 24자 까지 
#ifdef ENABLE_QUEST_CATEGORIES
	QUEST_SEND_CATEGORY_ID = 1 << 6,
#endif
};

enum EPVPModes
{
	PVP_MODE_NONE,
    PVP_MODE_AGREE,
    PVP_MODE_FIGHT,
    PVP_MODE_REVENGE,
};

enum
{
	FISHING_SUBHEADER_GC_START,
	FISHING_SUBHEADER_GC_STOP,
	FISHING_SUBHEADER_GC_REACT,
	FISHING_SUBHEADER_GC_SUCCESS,
	FISHING_SUBHEADER_GC_FAIL,
    FISHING_SUBHEADER_GC_FISH,
};

//////////////////////////////////////////////////////////////////////////
// Guild

enum
{
    GUILD_SUBHEADER_GC_LOGIN,
	GUILD_SUBHEADER_GC_LOGOUT,
	GUILD_SUBHEADER_GC_LIST,
	GUILD_SUBHEADER_GC_GRADE,
	GUILD_SUBHEADER_GC_ADD,
	GUILD_SUBHEADER_GC_REMOVE,
	GUILD_SUBHEADER_GC_GRADE_NAME,
	GUILD_SUBHEADER_GC_GRADE_AUTH, 
	GUILD_SUBHEADER_GC_INFO,
	GUILD_SUBHEADER_GC_COMMENTS,
    GUILD_SUBHEADER_GC_CHANGE_EXP,
    GUILD_SUBHEADER_GC_CHANGE_MEMBER_GRADE,
	GUILD_SUBHEADER_GC_SKILL_INFO,
	GUILD_SUBHEADER_GC_CHANGE_MEMBER_GENERAL,
	GUILD_SUBHEADER_GC_GUILD_INVITE,
    GUILD_SUBHEADER_GC_WAR,
    GUILD_SUBHEADER_GC_GUILD_NAME,
    GUILD_SUBHEADER_GC_GUILD_WAR_LIST,
    GUILD_SUBHEADER_GC_GUILD_WAR_END_LIST,
    GUILD_SUBHEADER_GC_WAR_POINT,
	GUILD_SUBHEADER_GC_MONEY_CHANGE,
	GUILD_SUBHEADER_GC_RANK_AND_POINT,
	GUILD_SUBHEADER_GC_BATTLE_STATS,
	GUILD_SUBHEADER_GC_LADDER_LIST,
	GUILD_SUBHEADER_GC_LADDER_SEARCH_RESULT,
	GUILD_SUBHEADER_GC_MEMBER_LASTPLAYED,
};

// SubHeader - Grade
enum
{
    GUILD_AUTH_ADD_MEMBER       = (1 << 0),
    GUILD_AUTH_REMOVE_MEMBER    = (1 << 1),
    GUILD_AUTH_NOTICE           = (1 << 2),
    GUILD_AUTH_SKILL            = (1 << 3),
#ifdef ENABLE_GUILD_SAFEBOX
	GUILD_AUTH_SAFEBOX_ITEM_GIVE	= (1 << 4),
	GUILD_AUTH_SAFEBOX_ITEM_TAKE	= (1 << 5),
	GUILD_AUTH_SAFEBOX_GOLD_GIVE	= (1 << 6),
	GUILD_AUTH_SAFEBOX_GOLD_TAKE	= (1 << 7),
#endif
#ifdef ENABLE_MELEY_LAIR_DUNGEON
	GUILD_AUTH_MELEY_ALLOW			= (1 << 8),
#endif
};

enum EGuildWarState
{
    GUILD_WAR_NONE,
    GUILD_WAR_SEND_DECLARE,
    GUILD_WAR_REFUSE,
    GUILD_WAR_RECV_DECLARE,
    GUILD_WAR_WAIT_START,
    GUILD_WAR_CANCEL,
    GUILD_WAR_ON_WAR,
    GUILD_WAR_END,

    GUILD_WAR_DURATION = 2*60*60, // 2시간
};

// SubHeader - Dungeon
enum
{
	DUNGEON_SUBHEADER_GC_TIME_ATTACK_START = 0,
	DUNGEON_SUBHEADER_GC_DESTINATION_POSITION = 1,
};

enum
{
    WALKMODE_RUN,
    WALKMODE_WALK,
};

enum SPECIAL_EFFECT
{
	SE_NONE,
	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,    
    SE_LEVELUP_ON_14_FOR_GERMANY,	//레벨업 14일때 ( 독일전용 )
    SE_LEVELUP_UNDER_15_FOR_GERMANY,//레벨업 15일때 ( 독일전용 )
    SE_PERCENT_DAMAGE1,
    SE_PERCENT_DAMAGE2,
    SE_PERCENT_DAMAGE3,    
	SE_AUTO_HPUP,
	SE_AUTO_SPUP,
	SE_EQUIP_RAMADAN_RING,			// 초승달의 반지를 착용하는 순간에 발동하는 이펙트
	SE_EQUIP_HALLOWEEN_CANDY,		// 할로윈 사탕을 착용(-_-;)한 순간에 발동하는 이펙트
	SE_EQUIP_HAPPINESS_RING,		// 크리스마스 행복의 반지를 착용하는 순간에 발동하는 이펙트
	SE_EQUIP_LOVE_PENDANT,		// 발렌타인 사랑의 팬던트(71145) 착용할 때 이펙트 (발동이펙트임, 지속이펙트 아님)
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	SE_ACCE_SUCESS_ABSORB,
	SE_ACCE_EQUIP,
	SE_ACCE_BACK,
#endif
#ifdef ENABLE_AGGREGATE_MONSTER_EFFECT
	SE_AGGREGATE_MONSTER_EFFECT,
#endif
	SE_EFFECT_HEALER,
#ifdef COMBAT_ZONE
	SE_COMBAT_ZONE_POTION,
#endif
};

enum EBlockAction
{
    BLOCK_EXCHANGE              = (1 << 0),
    BLOCK_PARTY_INVITE          = (1 << 1),
    BLOCK_GUILD_INVITE          = (1 << 2),
    BLOCK_WHISPER               = (1 << 3),
    BLOCK_MESSENGER_INVITE      = (1 << 4),
    BLOCK_PARTY_REQUEST         = (1 << 5),
};

enum
{
	CREATE_TARGET_TYPE_NONE,
	CREATE_TARGET_TYPE_LOCATION,
	CREATE_TARGET_TYPE_CHARACTER, 
#ifdef COMBAT_ZONE
	CREATE_TARGET_TYPE_COMBAT_ZONE,
#endif
};

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
enum
{
	ACCE_SUBHEADER_GC_SET_ITEM,
	ACCE_SUBHEADER_GC_CLEAR_SLOT,
	ACCE_SUBHEADER_GC_CLEAR_ALL,
	ACCE_SUBHEADER_GC_CLEAR_ONE,
};

enum
{
	ACCE_SUBHEADER_CG_REFINE_CHECKIN,
	ACCE_SUBHEADER_CG_REFINE_CHECKOUT,
	ACCE_SUBHEADER_CG_REFINE_ACCEPT,
	ACCE_SUBHEADER_CG_REFINE_CANCEL,
};
#endif

#ifdef ENABLE_GUILD_SAFEBOX
enum EGuildSafeboxSubHeader
{
	GUILD_SAFEBOX_SUBHEADER_SET_ITEM = 1,
	GUILD_SAFEBOX_SUBHEADER_REMOVE_ITEM = 2,
	GUILD_SAFEBOX_SUBHEADER_GOLD = 3,
	GUILD_SAFEBOX_SUBHEADER_OPEN = 4,
	GUILD_SAFEBOX_SUBHEADER_CLOSE = 5,
	GUILD_SAFEBOX_SUBHEADER_ENABLE = 6,
	GUILD_SAFEBOX_SUBHEADER_DISABLE = 7,
	GUILD_SAFEBOX_SUBHEADER_LOAD_LOG_START = 8,
	GUILD_SAFEBOX_SUBHEADER_LOAD_LOG = 9,
	GUILD_SAFEBOX_SUBHEADER_LOAD_LOG_DONE = 10,
	GUILD_SAFEBOX_SUBHEADER_APPEND_LOG = 11,
};

enum EGuildSafeboxLogTypes {
	GUILD_SAFEBOX_LOG_CREATE,
	GUILD_SAFEBOX_LOG_ITEM_GIVE,
	GUILD_SAFEBOX_LOG_ITEM_TAKE,
	GUILD_SAFEBOX_LOG_GOLD_GIVE,
	GUILD_SAFEBOX_LOG_GOLD_TAKE,
	GUILD_SAFEBOX_LOG_SIZE,
};
#endif

enum eInvSizeTypes
{
	INVENTORY_SIZE_TYPE_NORMAL,
	INVENTORY_SIZE_TYPE_UPPITEM,
	INVENTORY_SIZE_TYPE_SKILLBOOK,
	INVENTORY_SIZE_TYPE_STONE,
	INVENTORY_SIZE_TYPE_ENCHANT,
};

#ifdef ENABLE_DRAGONSOUL
enum EDragonSoulRefineWindowRefineType
{
	DragonSoulRefineWindow_UPGRADE,
	DragonSoulRefineWindow_IMPROVEMENT,
	DragonSoulRefineWindow_REFINE,
};

enum EPacketCGDragonSoulSubHeaderType
{
	DS_SUB_HEADER_OPEN,
	DS_SUB_HEADER_CLOSE,
	DS_SUB_HEADER_DO_UPGRADE,
	DS_SUB_HEADER_DO_IMPROVEMENT,
	DS_SUB_HEADER_DO_REFINE,
	DS_SUB_HEADER_REFINE_FAIL,
	DS_SUB_HEADER_REFINE_FAIL_MAX_REFINE,
	DS_SUB_HEADER_REFINE_FAIL_INVALID_MATERIAL,
	DS_SUB_HEADER_REFINE_FAIL_NOT_ENOUGH_MONEY,
	DS_SUB_HEADER_REFINE_FAIL_NOT_ENOUGH_MATERIAL,
	DS_SUB_HEADER_REFINE_FAIL_TOO_MUCH_MATERIAL,
	DS_SUB_HEADER_REFINE_SUCCEED,
};
#endif

#ifdef ENABLE_GAYA_SYSTEM
enum EGayaData {
	GAYA_SHOP_MAX_NUM = 12,
};
#endif

#ifdef ENABLE_EVENT_SYSTEM
enum EEventData
{
	EVENT_NAME_MAX_LEN = 30,
	EVENT_DESC_MAX_LEN = 256,
};
#endif

#ifdef ENABLE_COSTUME_BONUS_TRANSFER
enum EPacketGCCostumeBonusTransferSubHeaderType
{
	CBT_SUBHEADER_GC_OPEN,
	CBT_SUBHEADER_GC_CLOSE,
	CBT_SUBHEADER_GC_SET_ITEM,
	CBT_SUBHEADER_GC_DEL_ITEM,
	CBT_SUBHEADER_GC_CLEAR,
};

enum EPacketCGCostumeBonusTransferSubHeaderType
{
	CBT_SUBHEADER_CG_CHECKIN,
	CBT_SUBHEADER_CG_CHECKOUT,
	CBT_SUBHEADER_CG_ACCEPT,
	CBT_SUBHEADER_CG_CANCEL,
};
#endif

#ifdef ENABLE_RUNE_SYSTEM
enum ERuneData {
	RUNE_MAIN_COUNT = 4,
	RUNE_SUB_COUNT = 2,
};
#endif

enum EQuestTriggerIndex
{
	QUEST_TRIGGER_GAYA = 1,
	QUEST_TRIGGER_SOULS = 2,
	QUEST_TRIGGER_SOCKS = 3,
};

#ifdef ENABLE_EQUIPMENT_CHANGER
#define EQUIPMENT_PAGE_NAME_MAX_LEN 30
enum EquipChangerMisc {
	EQUIPMENT_CHANGER_WEAR_BODY,		// 0
	EQUIPMENT_CHANGER_WEAR_HEAD,		// 1
	EQUIPMENT_CHANGER_WEAR_FOOTS,		// 2
	EQUIPMENT_CHANGER_WEAR_WRIST,		// 3
	EQUIPMENT_CHANGER_WEAR_WEAPON,	// 4
	EQUIPMENT_CHANGER_WEAR_NECK,		// 5
	EQUIPMENT_CHANGER_WEAR_EAR,		// 6
	// EQUIPMENT_CHANGER_WEAR_UNIQUE1,	// 7
	// EQUIPMENT_CHANGER_WEAR_UNIQUE2,	// 8
	EQUIPMENT_CHANGER_WEAR_ARROW,		// 9
	EQUIPMENT_CHANGER_WEAR_SHIELD,	// 10
	// EQUIPMENT_CHANGER_WEAR_ABILITY1,  // 11
	// EQUIPMENT_CHANGER_WEAR_ABILITY2,  // 12
	// EQUIPMENT_CHANGER_WEAR_ABILITY3,  // 13
	// EQUIPMENT_CHANGER_WEAR_ABILITY4,  // 14
	// EQUIPMENT_CHANGER_WEAR_ABILITY5,  // 15
	// EQUIPMENT_CHANGER_WEAR_ABILITY6,  // 16
	// EQUIPMENT_CHANGER_WEAR_ABILITY7,  // 17
	// EQUIPMENT_CHANGER_WEAR_ABILITY8,  // 18
	EQUIPMENT_CHANGER_WEAR_COSTUME_BODY,	// 19
	EQUIPMENT_CHANGER_WEAR_COSTUME_HAIR,	// 20
	EQUIPMENT_CHANGER_WEAR_COSTUME_WEAPON,	// 21
	// EQUIPMENT_CHANGER_WEAR_RING1,			// 22	: 신규 반지슬롯1 (왼쪽)
	// EQUIPMENT_CHANGER_WEAR_RING2,			// 23	: 신규 반지슬롯2 (오른쪽)
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	EQUIPMENT_CHANGER_WEAR_ACCE,			// 24
#endif
#ifdef ENABLE_BELT_SYSTEM
	EQUIPMENT_CHANGER_WEAR_BELT,			// 25
#endif
	// EQUIPMENT_CHANGER_WEAR_UNIQUE3,
	// EQUIPMENT_CHANGER_WEAR_UNIQUE4,
	EQUIPMENT_CHANGER_WEAR_TOTEM,
	// WEAR_COSTUME_ACCE,
	EQUIPMENT_PAGE_MAX_PARTS,
};
#endif

#ifdef ENABLE_PET_ADVANCED
constexpr auto PET_SKILL_NORMAL_START = 0;
constexpr auto PET_SKILL_HEROIC_START = 3;
constexpr auto PET_SKILL_MAX_NUM = 5;
constexpr auto PET_SKILL_MAX_LEVEL = 20;
constexpr auto PET_SKILL_HEROIC_MAX_LEVEL = 10;
constexpr auto PET_MAX_LEVEL = 105;
constexpr auto PET_ATTR_MAX_NUM = 3;
constexpr auto PET_ITEM_VALUE_VNUM = 0;
constexpr auto PET_HEROIC_GRADE_NAME = "heroic";
constexpr auto PET_SKILLPOWER_MAX = 100;
#endif

#endif
#pragma pack(pop)